Update to Membrane Core 0.11, modify storage cleanup functionality
membraneframework/membrane_http_adaptive_stream_plugin pull request #62
Opened 2022-12-16 17:44 UTC by balins

- update to Core 0.11
- replace `{:cleanup, cleanup_fun}` notification with `cleanup_after` option, so cleanup runs after specified timeout if `Sink`/`SinkBin` was configured to do so

2023-01-12 11:52 UTC, mat-hek requested changes

2023-01-12 11:52 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/sink_bin.ex
> +            |> get_child(:sink)
Let's make it more concise

2023-01-12 11:52 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/sink_bin.ex
> +    {[spec: {structure, []}], state}
```suggestion
    {[spec: structure], state}
```

2023-01-12 11:52 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/sink_bin.ex
> +    {[spec: {structure, []}], state}
```suggestion
    {[spec: structure], state}
```

2023-01-13 08:31 UTC, balins commented on lib/membrane_http_adaptive_stream/sink.ex
> +        Process.sleep(timeout)
This is what we do in line 515

2023-01-13 09:39 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/sink.ex
> +        Process.sleep(timeout)
no idea why I haven't noticed 🤷

2023-01-13 09:39 UTC, mat-hek approved these changes

2023-01-13 11:11 UTC, merged