[ML-294] Add HLS EXT-X-PRELOAD-HINT tag
membraneframework/membrane_http_adaptive_stream_plugin pull request #77
Opened 2023-05-05 13:07 UTC by LVala

Closes [ML-294](https://membraneframework.atlassian.net/browse/ML-294).

2023-05-08 09:30 UTC, LVala commented
Additionally, fixed bug with `hls.ex`, that created empty playlist for audio tracks, when no segments have been received yet.

2023-05-09 08:44 UTC, Karolk99 requested changes

2023-05-09 08:44 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/hls.ex
> +    # hls.js currently does not support EXT-X-PRELOAD_HINT tag
This comment is irrelevant. Hls.js is just a javascript library with nothing to do with this code.

2023-05-09 08:44 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/hls.ex
> +  end
I would try something like that: 
```suggestion
    case Qex.last(track.segments) do
  :empty -> ""

  %Segment{type: :partial, name: name, parts: parts} = last_segment ->
    bytes = Enum.reduce(parts, 0, fn part, acc -> acc + part.size end)
    "#EXT-X-PRELOAD-HINT:TYPE=PART,URI=\"#{name}\",BYTERANGE-START=#{bytes}"

  %Segment{type: :full} = last_segment ->
    name = track.segment_naming_fun.(track) <> track.segment_extension
    "#EXT-X-PRELOAD-HINT:TYPE=PART,URI=\"#{name}\",BYTERANGE-START=0"
end
```

2023-05-09 13:44 UTC, Karolk99 approved these changes

2023-05-09 14:39 UTC, merged