Delta manifest / Skipping old segments in ll-hls
membraneframework/membrane_http_adaptive_stream_plugin pull request #78
Opened 2023-05-12 08:48 UTC by blazpie

PR adds option to skip old segments in live playlist for ll-hls.

1. Adds CAN-SKIP-UNTIL tag when playlist is longer then 6 regular segments
2. Creates delta manifests for streams longer than 6 segments by adding `EXT-X-SKIP` tag and skipping old segments
3. Creates separate `*.m3u8` files fith `_delta` suffix to store delta playlist. Files should be send to client instead of regular manifest when request contains `_HLS_SKIP` parameter

2023-05-15 14:12 UTC, Karolk99 requested changes
It looks good but we need some tests for this new tag.

2023-05-15 14:12 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/hls.ex
> +  defp can_skip_until(_can_skip_segments_duration), do: ""
```suggestion
  defp can_skip_until(duration) when duration > 0,
    do: ",CAN-SKIP-UNTIL=#{duration}"

  defp can_skip_until(_duration), do: ""
```

2023-05-15 14:44 UTC, mat-hek requested changes

2023-05-15 14:44 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/hls.ex
> +  end
Since this is only used in one place, let's assign it to a variable there instead of creating another function. It's going to read better.

2023-05-15 14:44 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/hls.ex
> +        nil
this is passed to `serialize_ll_hls_tags`, which seems to assume it's a number

2023-05-18 10:36 UTC, blazpie commented on lib/membrane_http_adaptive_stream/hls.ex
> +  @min_segments_in_delta_playlist 6
RFC doesn't specify any value here. I've found mentioned in one article (https://www.linkedin.com/pulse/apples-implementation-low-latency-hls-explained-phil-harrison) that CAN-SKIP-UNTIL should have a value of 6 segments before the live boundary. And this value is a consequence of that info. But I've tested it also on smaller values (eg. 2 segments) and it also seems to work fine too. Any constant value bigger than 1 will be good here IMO. I've chosen 6.

2023-05-18 11:53 UTC, mat-hek approved these changes

2023-05-18 15:17 UTC, Karolk99 commented on test/membrane_http_adaptive_stream/integration_test/sink_bin_integration_test.exs
> +      Process.sleep(10_000)
I don't think we need to additionally wait for the files to be safe, `end_of_stream` ensures us that everything is already saved.
```suggestion
```
You can also remove sleep() in two other cases.

2023-05-19 11:51 UTC, merged