Add encoding info to master manifest
membraneframework/membrane_http_adaptive_stream_plugin pull request #81
Opened 2023-06-12 14:14 UTC by blazpie

2023-06-16 08:52 UTC, Karolk99 requested changes

2023-06-16 08:52 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/manifest/track.ex
> +                  encoding: []
All of those new fields have default values so either all of them should be enforced or not.

2023-06-16 08:52 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/sink.ex
> +
I would instead return 
```
%{resolution: _, encoding_info: -}
```

2023-06-16 08:52 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/track_info.ex
> +  Currently retrive information about: resolution, framerate and codecs.
TrackInfo doesn't retrieve information about framerate

2023-06-16 08:52 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/track_info.ex
> +          :resolution => {non_neg_integer(), non_neg_integer()} | nil
```suggestion
          :encoding_info => (:avc1 | :mp4a) => map(),
          :resolution => {non_neg_integer(), non_neg_integer()} | nil
```

2023-06-16 08:52 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/track_info.ex
> +        moov_children = parsed |> (fn el -> get_in(el, [:moov, :children]) end).()
it's no no

2023-06-16 09:25 UTC, Karolk99 approved these changes

2023-06-16 09:25 UTC, Karolk99 commented on lib/membrane_http_adaptive_stream/track_info.ex
> +  end
it's not compatible with API

2023-06-16 10:28 UTC, mat-hek requested changes

2023-06-16 10:28 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/bandwidth_calculator.ex
> +      |> then(fn {num, denom} -> num / denom end)
If we operate on ratios all the time, why handle a fraction manually here?

2023-06-16 10:28 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/sink_bin.ex
> +      maximal_framerate: [
```suggestion
      max_framerate: [
```

2023-06-16 10:28 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/track_info.ex
> +end
Let's send make MP4 payloaders and the CMAF muxer send this information in the stream format instead of parsing the header

2023-06-30 14:41 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/bandwidth_calculator.ex
> +      |> then(fn {num, denom} -> num / denom end)
bump

2023-06-30 14:49 UTC, mat-hek approved these changes

2023-06-30 14:49 UTC, mat-hek commented on lib/membrane_http_adaptive_stream/bandwidth_calculator.ex
> +      |> then(fn {num, denom} -> num / denom end)
bump

2023-07-07 13:44 UTC, Karolk99 approved these changes

2023-07-11 05:48 UTC, merged